
var data = [

  {
    "ID":10201005,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Wes: We had all the comforts",
    "Seq\nNum":5,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s10n05-wes-we-had-all-the-comforts.mp3",
    "Done":"",
    "Transition":"",
    "Playback":"Not Looped",
    "Notes":"\"The shantyboat was small, but livable. We had all the comforts of home. A kitchen, a work table, lots of light and breeze, and a well-stocked project library, of river memoirs, references books, and trashy novels. Everything you could need.\""
  },
  {
    "ID":10201010,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Small waves lapping",
    "Seq\nNum":10,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s10n10-small-waves-lapping.mp3",
    "Done":"x",
    "Transition":"",
    "Playback":"Looped",
    "Notes":"through whole chapter?"
  },
  {
    "ID":10201012,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Shantyboat sunny window loop",
    "Seq\nNum":12,
    "Producer":"Wes",
    "Media":"video",
    "Filename":"p10c20s10n12-shantyboat-sunny-window-loop.mp4",
    "Done":"x",
    "Transition":"push",
    "Playback":"Looped",
    "Notes":""
  },
  {
    "ID":10201015,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Shantyboat from above w Hazel",
    "Seq\nNum":15,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n15-shantyboat-from-above-w-hazel.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201020,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty windows",
    "Seq\nNum":20,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n20-doty-windows.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201025,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty galley",
    "Seq\nNum":25,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n25-doty-galley.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201030,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty worktable",
    "Seq\nNum":30,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n30-doty-worktable.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201035,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty loft",
    "Seq\nNum":35,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n35-doty-loft.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201040,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty fern",
    "Seq\nNum":40,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n40-doty-fern.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201045,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty library",
    "Seq\nNum":45,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n45-doty-library.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201050,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty head",
    "Seq\nNum":50,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n50-doty-head.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10201060,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Comfort",
    "Scene Num":10,
    "Description":"Doty under bridge",
    "Seq\nNum":60,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s10n60-doty-under-bridge.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"Looped",
    "Notes":""
  },
  {
    "ID":10202005,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Music",
    "Scene Num":20,
    "Description":"Wes: Music was important",
    "Seq\nNum":5,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s20n05-wes-music-was-important.mp3",
    "Done":"",
    "Transition":"",
    "Playback":"Not Looped",
    "Notes":"\"The voyage of the Doty was a journey steeped in mood and ambiance. So from the beginning, music was important. We had an old radio on the boat and of course a banjo.\""
  },
  {
    "ID":10202010,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Music",
    "Scene Num":20,
    "Description":"Bob Wills - Stay a Little Longer",
    "Seq\nNum":10,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s20n10-bob-wills-stay-a-little-longer.mp3",
    "Done":"x",
    "Transition":"",
    "Playback":"Looped",
    "Notes":""
  },
  {
    "ID":10202012,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Music",
    "Scene Num":20,
    "Description":"Radio band tuning",
    "Seq\nNum":12,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s20n12-radio-band-tuning.mp3",
    "Done":"x",
    "Transition":"",
    "Playback":"Looped",
    "Notes":""
  },
  {
    "ID":10202015,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Music",
    "Scene Num":20,
    "Description":"Closeup of radio",
    "Seq\nNum":15,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s20n15-closeup-of-radio.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203005,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Wes: We had safety equipment",
    "Seq\nNum":5,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s30n05-wes-we-had-safety-equipment.mp3",
    "Done":"",
    "Transition":"",
    "Playback":"Not Looped",
    "Notes":"\"We were a floating house, but also a boat. So we had all the usual boating safety equipment too. River maps, flotation devices, radio, anchors, bilge pump, and so on. We were pushed about by our little motor Mr. Johnson, a 60s era 9.5HP Johnson outboard which wasn't always completely reliable.\""
  },
  {
    "ID":10203010,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"USGS Maps",
    "Seq\nNum":10,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n10-usgs-maps.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203010,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Life vests",
    "Seq\nNum":10,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n10-life-vests.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203015,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Life ring",
    "Seq\nNum":15,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n15-life-ring.jpg",
    "Done":"",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203020,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Marine radio",
    "Seq\nNum":20,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n20-marine-radio.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203025,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Anchors",
    "Seq\nNum":25,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n25-anchors.jpg",
    "Done":"",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203027,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Tippy the canoe",
    "Seq\nNum":27,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n27-tippy-the-canoe.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203030,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Mr. Johnson in place",
    "Seq\nNum":30,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n30-mr-johnson-in-place.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10203035,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Equipment",
    "Scene Num":30,
    "Description":"Mr. Johnson disassembled",
    "Seq\nNum":35,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s30n35-mr-johnson-disassembled.jpg",
    "Done":"x",
    "Transition":"flare",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10204005,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Food",
    "Scene Num":40,
    "Description":"Wes: We ate pretty well",
    "Seq\nNum":5,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s40n05-wes-we-ate-pretty-well.mp3",
    "Done":"",
    "Transition":"",
    "Playback":"",
    "Notes":"\"Since the Doty had a full galley, we ate pretty well. And we had plenty to drink. People brought us lots of beer and we had a well-stocked liquor cabinet. Kentucky bourbon and White Russians were the crew's drinks of choice."
  },
  {
    "ID":10204010,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Food",
    "Scene Num":40,
    "Description":"Bacon frying",
    "Seq\nNum":10,
    "Producer":"Wes",
    "Media":"video",
    "Filename":"p10c20s40n10-bacon-frying.mp4",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10204012,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Food",
    "Scene Num":40,
    "Description":"Pancakes",
    "Seq\nNum":12,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s40n12-pancakes.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10204015,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Food",
    "Scene Num":40,
    "Description":"Liquor bottles",
    "Seq\nNum":15,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s40n15-liquor-bottles.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10204020,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"Food",
    "Scene Num":40,
    "Description":"White Russians",
    "Seq\nNum":20,
    "Producer":"Wes",
    "Media":"image",
    "Filename":"p10c20s40n20-white-russians.jpg",
    "Done":"x",
    "Transition":"push",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10205003,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"End",
    "Scene Num":50,
    "Description":"Daniella wayfaring stranger",
    "Seq\nNum":3,
    "Producer":"Wes",
    "Media":"audio",
    "Filename":"p10c20s50n03-daniella-wayfaring-stranger.mp3",
    "Done":"",
    "Transition":"",
    "Playback":"",
    "Notes":""
  },
  {
    "ID":10205005,
    "Path Name":"Voyage of the Doty",
    "Path Num":10,
    "Chapter Name":"Life on the Shantyboat",
    "Chap Num":20,
    "Scene Name":"End",
    "Scene Num":50,
    "Description":"Daniella playing banjo loop",
    "Seq\nNum":5,
    "Producer":"Wes",
    "Media":"video",
    "Filename":"p10c20s50n05-daniella-playing-banjo-loop.mp4",
    "Done":"x",
    "Transition":"push",
    "Playback":"Looped",
    "Notes":""
  }

] ;

var newData = { name :"root", properties : [] },
    levels = ["Path Num","Chap Num","Scene Num"];

    var newData = {
        "name":"root", 
        "properties": 
            d3.nest()
                .key(function(d){ return d.dep})
                .key(function(d){return d.name})
                .entries(data)
    }
    
    $("body").text(JSON.stringify(newData))
